### ISSUE TITLE
Xcribe breaks when Date struct is given as params

### ISSUE THREAD

**Issue by thiamsantos** [brainn-co/xcribe#28]
The solution for me was to convert the Date struct to `iso8601`.

Maybe we could mimic the behaviour from plug when processing that test, it was implicitly converting the date to a string format. Also, I don't know but we could in some way improve our error handling, helping the user to find the offender code, in this case, I had to search between all the tests the one that was passing a date directly, the stack trace from xcribe helped me identify the problem but not the part of the code that was causing it.

Example of test:

```elixir
base_date = Date.utc_today()
second_date = Date.add(base_date, -3)

params = %{
  "payments" => [
    %{"date" => second_date},
    %{"date" => base_date}
  ]
}

body = %{"data" => params}
path = Routes.reclaiming_path(conn, :update, reclaiming_id)

assert %{"errors" => errors} =
          conn
          |> with_access_token()
          |> patch(path, body)
          |> document()
          |> json_response(:unprocessable_entity)
```

Stacktrace
```
** (EXIT from #PID<0.94.0>) exited in: GenServer.stop(#PID<0.1878.0>, :normal, :infinity)
    ** (EXIT) exited in: :sys.terminate(#PID<0.1878.0>, :normal, :infinity)
        ** (EXIT) an exception was raised:
            ** (Protocol.UndefinedError) protocol Enumerable not implemented for ~D[2020-05-04] of type Date (a struct). This protocol is implemented for the following type(s): Ecto.Adapters.SQL.Stream, Postgrex.Stream, DBConnection.PrepareStream, DBConnection.Stream, Scrivener.Page, IO.Stream, List, Function, HashDict, Map, GenEvent.Stream, File.Stream, HashSet, MapSet, Range, Stream, Date.Range
                (elixir 1.10.1) lib/enum.ex:1: Enumerable.impl_for!/1
                (elixir 1.10.1) lib/enum.ex:141: Enumerable.reduce/3
                (elixir 1.10.1) lib/enum.ex:3383: Enum.reduce/3
                (xcribe 0.3.0) lib/swagger/formatter.ex:288: Xcribe.Swagger.Formatter.schema_add_properties/3
                (xcribe 0.3.0) lib/swagger/formatter.ex:298: anonymous fn/3 in Xcribe.Swagger.Formatter.reduce_properties/2
                (stdlib 3.12.1) maps.erl:232: :maps.fold_1/3
                (xcribe 0.3.0) lib/swagger/formatter.ex:288: Xcribe.Swagger.Formatter.schema_add_properties/3
                (xcribe 0.3.0) lib/swagger/formatter.ex:283: Xcribe.Swagger.Formatter.schema_add_items/3
                (xcribe 0.3.0) lib/swagger/formatter.ex:298: anonymous fn/3 in Xcribe.Swagger.Formatter.reduce_properties/2
                (stdlib 3.12.1) maps.erl:232: :maps.fold_1/3
                (xcribe 0.3.0) lib/swagger/formatter.ex:288: Xcribe.Swagger.Formatter.schema_add_properties/3
                (xcribe 0.3.0) lib/swagger/formatter.ex:298: anonymous fn/3 in Xcribe.Swagger.Formatter.reduce_properties/2
                (stdlib 3.12.1) maps.erl:232: :maps.fold_1/3
                (xcribe 0.3.0) lib/swagger/formatter.ex:288: Xcribe.Swagger.Formatter.schema_add_properties/3
                (xcribe 0.3.0) lib/swagger/formatter.ex:205: Xcribe.Swagger.Formatter.media_type_object/2
                (xcribe 0.3.0) lib/swagger/formatter.ex:189: Xcribe.Swagger.Formatter.path_item_object_add_request_body/2
                (xcribe 0.3.0) lib/swagger/formatter.ex:46: Xcribe.Swagger.Formatter.path_item_object_from_request/1
                (xcribe 0.3.0) lib/swagger/swagger.ex:45: Xcribe.Swagger.paths_object_func/2
                (elixir 1.10.1) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
                (xcribe 0.3.0) lib/swagger/swagger.ex:25: Xcribe.Swagger.mount_data_in_raw_object/2

```

**Comment by antedeguemon** [comment]
Here is Plug's parameters stringify func:
https://github.com/elixir-plug/plug/blob/master/lib/plug/adapters/test/conn.ex#L148
