### ISSUE TITLE
Xcribe breaks when there is no pipelines configured

### ISSUE THREAD

**Issue by thiamsantos** [brainn-co/xcribe#48]
The line https://github.com/brainn-co/xcribe/blob/master/lib/xcribe/conn_parser.ex#L74 assumes that it would always have a pipeline for the endpoint. For that reason when there is no pipelines for the endpoint.

```
1) test GET /version show version (MyAppWeb.VersionControllerTest)
test/yield_web/controllers/version_controller_test.exs:7
** (FunctionClauseError) no function clause matching in Xcribe.ConnParser.resource_group/1

The following arguments were given to Xcribe.ConnParser.resource_group/1:

    # 1
    %{conn: nil, log: :debug, path_params: %{}, pipe_through: [], plug: MyAppWeb.VersionController, plug_opts: :show, route: "/version"}

Attempted function clauses (showing 1 out of 1):

    defp resource_group(%{pipe_through: [head | _rest]})

code: ConfigHelper.with_config(:version, "0.0.1", fn ->
stacktrace:
  (xcribe 0.7.3) lib/xcribe/conn_parser.ex:74: Xcribe.ConnParser.resource_group/1
  (xcribe 0.7.3) lib/xcribe/conn_parser.ex:42: Xcribe.ConnParser.parse_conn/3
  test/my_app_web/controllers/version_controller_test.exs:14: anonymous fn/1 in MyAppWeb.VersionControllerTest."test GET /version show version"/1
  (my_app 0.1.0) test/support/config_helper.ex:7: MyApp.ConfigHelper.with_config/3
  test/yield_web/controllers/version_controller_test.exs:8: (test)
```

**Comment by antedeguemon** [comment]
The only formatter that uses `resource_group` is `:api_blueprint`.

 I will pick this issue. (may I? :smile:)
